In [ ]:
'''
listar dados lendo uma base de dados externa
29/04/2026
'''
#dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'  # link na internet da base de dados externa
dados = 'BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, sep=';', encoding='latin1')

#df
df.columns
#df.head(10)
#df.shape
#df.tail(10)

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='object')

In [34]:
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_cisp = df_furto_celular_cisp.sort_values(by='furto_celular', ascending=False)
df_furto_celular_cisp

     cisp  furto_celular
12     16          25709
2       5          24695
10     14          18286
8      12          16929
0       1          15952
..    ...            ...
87    104             72
77     92             65
114   138             55
131   157             55
129   155             47

[138 rows x 2 columns]

In [39]:
df_aaapai_cisp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_cisp = df_aaapai_cisp.sort_values(by='aaapai', ascending=False)
df_aaapai_cisp

     cisp  aaapai
104   126  3661.0
8      12  3655.0
10     14  3346.0
65     74  3343.0
12     16  3179.0
..    ...     ...
130   156    18.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [ ]:
df_aaapai_cisp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_cisp = df_aaapai_cisp.sort_values(by='aaapai', ascending=False)
df_aaapai_cisp